CREATE DATABASE projeto_final_avanti;
-- CREATE USER prismaorm WITH PASSWORD '1234567890' CREATEDB;

CREATE DATABASE IF NOT EXISTS products_db;
CREATE DATABASE IF NOT EXISTS categories_db;
CREATE DATABASE IF NOT EXISTS stocks_db;
CREATE DATABASE IF NOT EXISTS users_db;
CREATE DATABASE IF NOT EXISTS orders_db;